# Generated by Django 5.0.9 on 2026-08-24 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('holes', '0001_enable_postgis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('hole_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('hole_name', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('easting', models.FloatField(blank=True, null=True)),
                ('northing', models.FloatField(blank=True, null=True)),
                ('elevation_m', models.FloatField(blank=True, null=True)),
                ('borehole_length_m', models.FloatField(blank=True, null=True)),
                ('inclination_deg', models.FloatField(default=-90.0)),
                ('azimuth_deg', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'holes',
                'ordering': ['hole_id'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_no', models.IntegerField(blank=True, null=True)),
                ('depth_from_m', models.FloatField()),
                ('depth_to_m', models.FloatField()),
                ('mineral_1', models.CharField(blank=True, max_length=64)),
                ('mineral_1_pct', models.FloatField(blank=True, null=True)),
                ('mineral_2', models.CharField(blank=True, max_length=64)),
                ('mineral_2_pct', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('quality_flag', models.CharField(choices=[('ok', 'ok'), ('low_signal', 'low signal'), ('missing', 'missing')], default='ok', max_length=32)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='holes.hole')),
            ],
            options={
                'db_table': 'measurements',
                'ordering': ['hole_id', 'depth_from_m'],
                'indexes': [models.Index(fields=['hole', 'depth_from_m'], name='measurement_hole_id_7c8fc5_idx'), models.Index(fields=['is_anomaly'], name='measurement_is_anom_fe1ffe_idx')],
            },
        ),
    ]
