# Generated by Django 5.0.9 on 2026-09-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holes', '0003_spatial_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='hole',
            name='confidential',
            field=models.BooleanField(default=False),
        ),
    ]
