# Generated by Django 5.0.9 on 2026-09-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holes', '0004_hole_confidential'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='why',
            field=models.TextField(blank=True),
        ),
    ]
