# Generated by Django 5.0.9 on 2026-09-10 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holes', '0005_measurement_why'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreTray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tray_no', models.IntegerField()),
                ('depth_from_m', models.FloatField()),
                ('depth_to_m', models.FloatField()),
                ('image', models.CharField(blank=True, max_length=255)),
                ('swir_vnir_mineral', models.CharField(blank=True, max_length=64)),
                ('swir_vnir_group', models.CharField(blank=True, max_length=64)),
                ('swir_vnir_wt_pct', models.FloatField(blank=True, null=True)),
                ('swir_vnir_pct_of_tray', models.FloatField(blank=True, null=True)),
                ('tir_mineral', models.CharField(blank=True, max_length=64)),
                ('tir_group', models.CharField(blank=True, max_length=64)),
                ('tir_wt_pct', models.FloatField(blank=True, null=True)),
                ('tir_pct_of_tray', models.FloatField(blank=True, null=True)),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trays', to='holes.hole')),
            ],
            options={
                'db_table': 'core_trays',
                'ordering': ['hole_id', 'depth_from_m'],
            },
        ),
    ]
